### ISSUE TITLE
Navbar displaying problems with Safari macOS / iOS

### ISSUE THREAD

**Issue by corrieriluca** [Epidocs/epita.it#27]
I've been experiencing some problems with EPITA.it on both Safari iOS and macOS relating to how the navigation bar displays itself. So I trying to solve this problem by looking on the CSS code attached to the `navbar` class. 

I found that disabling the `display: flex;` property in the `navbar` class in the `bootstrap.css` stylesheet line 3920 solves the problem both on macOS and iOS, and also doesn't alter the appearance of the navbar on other web engines (tested on Firefox and Chromium). 

Below are some screenshots demonstrating the problem and its solution :

![Capture d’écran 2019-09-28 à 19 53 19](https://user-images.githubusercontent.com/43756260/65820769-5345cd80-e22d-11e9-8556-d4a33ba7b609.jpg)
![Capture d’écran 2019-09-28 à 19 59 15](https://user-images.githubusercontent.com/43756260/65820773-53de6400-e22d-11e9-84fc-f257f94ae597.png)
![Capture d’écran 2019-09-28 à 19 58 24](https://user-images.githubusercontent.com/43756260/65820770-5345cd80-e22d-11e9-8387-2916b6bc1f29.jpg)
![Capture d’écran 2019-09-28 à 19 59 08](https://user-images.githubusercontent.com/43756260/65820772-5345cd80-e22d-11e9-9eab-a0b375b50e85.png)

Now the challenge is to incorporate these changes to the CSS code since the Bootstrap CSS is loaded from the header...

**Comment by matiboux** [comment]
Let's just add a overriding rule in the `assets/css/style.css` file.

_**Note**: It would be worth checking if Bootstrap is aware of the issue. I haven't found anything on this._
