### ISSUE TITLE
The Community and Resources tabs should have their contents merged?

### ISSUE THREAD

**Issue by utybo** [Epidocs/epita.it#39]
The current menus for Community and Resources don't make much sense, especially with just two items which are relatively small pages in each. Moreover, they hinder the discoverability of their content, as I don't think people would automatically think about looking for documentation in the "resources" tabs, especially when people generally only care about the home page.

In my opinion, these menus should be united into one bigger page each: one community (with the students clubs and community contents) and one "resources" (although a better name can probably be found somewhere) with both documentation and the EpiDocs resources in a single category (kind of like the current Documentation and Guides categories).

I don't know if that issue was clear -- writing those at 3 am is not easy

**Comment by matiboux** [comment]
Theses pages are different from each other. Merging them wouldn't make much sense.
