### ISSUE TITLE
No proper LICENSE for the project

### ISSUE THREAD

**Issue by utybo** [Epidocs/epita.it#41]
I just noticed that there is no LICENSE file anywhere in this repository. It would be a good idea to add one, for various reasons, including the fact that, as of right now, making derivatives, forks and PRs is "illegal" (since the default license in French law and probably in the US as well is that you (@matiboux) put a "All rights reserved" upon the content).

I would suggest a [Creative Commons license](https://creativecommons.org/choose) like the [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) or a software license like the [MIT license](https://en.wikipedia.org/wiki/MIT_License)

**Comment by matiboux** [comment]
Nothing as such is illegal, as specified by Github's Terms of Service.
> « By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control). »
> — https://help.github.com/en/github/site-policy/github-terms-of-service

A proper license should be adopted and I shall look into that later.

**Comment by utybo** [comment]
That's more of a technicality of having your project hosted on GitHub than a intrinsic property of the *project* itself, but I get what you're saying. I'm pretty sure this line in the ToS is mostly GitHub trying to dodge copyright lawsuits in case the project owner... forgot to put a license :P

**Comment by matiboux** [comment]
I think it's mostly Github not wanting to prevent users from forking the projects missing a license. Many of Github features are about linking repos between them, and workarounds would be worse. Uh, anyway, I won't detail any further my thinking but you can imagine the problems.
